import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import NavBar from '../components/NavBar';
import { trpc } from "../utils/trpc";
import LatestPosts from "../components/LatestPosts";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>My web app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-[#ebf4f5] to-[#b5c6e0] min-h-screen ">
        <NavBar/>
        <div className="flex flex-col items-center justify-center ">
          <div className="container flex flex-col gap-12 px-4 py-16 items-center justify-center ">
            {/* Header */}
            <div className="text-7xl font-light font-grotesk tracking-wide">
              Welcome.
            </div>
            <div className="text-lg font-light font-grotesk tracking-tight">
              I'm cooking up a new web app using the <Link href="https://create.t3.gg/" className="underline font-bold hover:text-black/70">T3 stack</Link>.
            </div>
          </div>
        </div>
        <div className="text-lg">
            <LatestPosts/>
        </div>
      </main>
    </>
  );
};

export default Home;
